---
title: "Week 6 - Metadata standards"
---

## Learning goals

-   Understand the role of metadata in facilitating the management, discovery, interoperability, and reuse of digital resources and research data.
-   Recognize the importance of adhering to domain-specific metadata standards and determining which standard should be used.
-   Acquire familiarity with the overall structure of the Ecological Metadata Language (EML) schema and the anatomy of an EML record.
-   Programmatically create EML metadata records using R.

## Slides and other materials

[slides-06.pptx](slides-06.pptx)

[Class data GitHub repository, week 6](https://github.com/UCSB-Library-Research-Data-Services/bren-meds213-spring-2023-class-data/tree/main/week6) for in-class exercise

Related resources:

-   [Research Data Alliance (RDA) Metadata Standard Catalog](https://rdamsc.bath.ac.uk).
-   [EML Schema Documentation](https://eml.ecoinformatics.org/).
-   [EML Best Practices](https://ediorg.github.io/data-package-best-practices/eml-best-practices.html).
-   [Creating EML records in R](https://github.com/ropensci/EML).
-   [EzEML - Ecological Data Initiative (EDI)](https://ezeml.edirepository.org/).
-   [Excel to EML](https://github.com/lkuiucsb/Excel-to-EML).
-   [capemlGIS](https://caplter.github.io/capemlGIS/) - a package that extends the [CAPLTER/capeml](https://github.com/CAPLTER/capeml) to facilitate the creation of EML spatialRaster and spatialVector objects and metadata.

## Recommended readings

1.  Gries, C., Hanson, P. C., O'Brien, M., Servilla, M., Vanderbilt, K., & Waide, R. (2023). The Environmental Data Initiative: Connecting the past to the future through data reuse. Ecology and Evolution, 13(1), e9592. <https://doi.org/10.1002/ece3.9592>

2.  Leipzig, J., Nüst, D., Hoyt, C. T., Ram, K., & Greenberg, J. (2021). The role of metadata in reproducible computational research. Patterns, 2(9), <https://doi.org/10.1016/j.patter.2021.100322>

## Homework

[EML record](hw-06.qmd)
